// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 93c2e84eadc6f777 "Portofolio", do not edit manually */
"use client";

// virtual:nav-bar-links
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rjfVl88mUXTB7aIghRam/R3yeWMgqh7RWFVgbTNTH/YSYwvHiaF.js
import { jsx as _jsx4, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	ComponentViewportProvider as ComponentViewportProvider2,
	cx as cx2,
	getFonts as getFonts2,
	ResolveLinks,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useRouter,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React4 from "react";
import { useRef as useRef3 } from "react";

// /:https://framerusercontent.com/modules/gWFumn3jFcGYz6tuD9Hb/t69I5ux4Wsx24Gu7oJfa/GWxCRUDr_.js
import { jsx as _jsx3, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType3,
	cx,
	getFonts,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React3 from "react";

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
import { jsx as _jsx2 } from "react/jsx-runtime";
import * as React2 from "react";
import { useState, useEffect, useRef } from "react";
import {
	addPropertyControls,
	ControlType as ControlType2,
	RenderTarget,
} from "unframer";

// /:https://framerusercontent.com/modules/DyldKav0OOAWR3bCAlhK/8c3l9FzyOlGpbPncYhfc/nullstate.js
import { jsx as _jsx } from "react/jsx-runtime";
import * as React from "react";
var containerStyles = {
	width: "100%",
	height: "100%",
	display: "flex",
	justifyContent: "center",
	alignItems: "center",
};
var emptyStateStyle = {
	...containerStyles,
	borderRadius: 6,
	background: "rgba(149, 149, 149, 0.1)",
	border: "1px dashed rgba(149, 149, 149, 0.15)",
	color: "#a5a5a5",
	flexDirection: "column",
};
var NullState = /* @__PURE__ */ React.forwardRef((_, ref) => {
	return <div style={emptyStateStyle} ref={ref} />;
});

// /:https://framerusercontent.com/modules/8tFVJ9SCM5akQRM0UzVD/YkxZV5bKC4LrRDEdvAgQ/home.js
var r;
var s = (o) => {
	if (!r) {
		const n = o.forwardRef(
			({ color: t = "currentColor", size: e = 24, ...i }, l) => {
				return o.createElement(
					"svg",
					{
						ref: l,
						xmlns: "http://www.w3.org/2000/svg",
						width: e,
						height: e,
						viewBox: "0 0 24 24",
						fill: "none",
						stroke: t,
						strokeWidth: "2",
						strokeLinecap: "round",
						strokeLinejoin: "round",
						...i,
					},
					o.createElement("path", {
						d: "M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z",
					}),
					o.createElement("polyline", {
						points: "9 22 9 12 15 12 15 22",
					}),
				);
			},
		);
		(n.displayName = "Home"), (r = n);
	}
	return r;
};

// /:https://framerusercontent.com/modules/Ma20hU0GGRxLxZphbywl/OSpwWF91FHPVFyQJjMHt/utils.js
import { useMemo } from "react";
import { ControlType } from "unframer";
var defaultEvents = {
	onClick: {
		type: ControlType.EventHandler,
	},
	onMouseDown: {
		type: ControlType.EventHandler,
	},
	onMouseUp: {
		type: ControlType.EventHandler,
	},
	onMouseEnter: {
		type: ControlType.EventHandler,
	},
	onMouseLeave: {
		type: ControlType.EventHandler,
	},
};
var findByArray = (arr, search) =>
	arr.find((a) => a.toLowerCase().includes(search));
function useIconSelection(
	iconKeys2,
	selectByList,
	iconSearch = "",
	iconSelection,
	lowercaseIconKeyPairs2,
) {
	const iconSearchResult = useMemo(() => {
		if (
			iconSearch == null ||
			(iconSearch === null || iconSearch === void 0
				? void 0
				: iconSearch.length) === 0
		)
			return null;
		const iconSearchTerm = iconSearch.toLowerCase().replace(/-|\s/g, "");
		var _iconSearchTerm;
		const searchResult =
			(_iconSearchTerm = lowercaseIconKeyPairs2[iconSearchTerm]) !== null &&
			_iconSearchTerm !== void 0
				? _iconSearchTerm
				: findByArray(iconKeys2, iconSearchTerm);
		return searchResult;
	}, [iconSelection, iconSearch]);
	const name = selectByList ? iconSelection : iconSearchResult;
	return name;
}

// /:https://framerusercontent.com/modules/f0DboytQenYh21kfme7W/zb1zVBMZJKgPMiedOi0y/Feather.js
var iconKeys = [
	"activity",
	"airplay",
	"alert-circle",
	"alert-octagon",
	"alert-triangle",
	"align-center",
	"align-justify",
	"align-left",
	"align-right",
	"anchor",
	"aperture",
	"archive",
	"arrow-down",
	"arrow-down-circle",
	"arrow-down-left",
	"arrow-down-right",
	"arrow-left",
	"arrow-left-circle",
	"arrow-right",
	"arrow-right-circle",
	"arrow-up",
	"arrow-up-circle",
	"arrow-up-left",
	"arrow-up-right",
	"at-sign",
	"award",
	"bar-chart",
	"bar-chart-2",
	"battery",
	"battery-charging",
	"bell",
	"bell-off",
	"bluetooth",
	"bold",
	"book",
	"book-open",
	"bookmark",
	"box",
	"briefcase",
	"calendar",
	"camera",
	"camera-off",
	"cast",
	"check",
	"check-circle",
	"check-square",
	"chevron-down",
	"chevron-left",
	"chevron-right",
	"chevron-up",
	"chevrons-down",
	"chevrons-left",
	"chevrons-right",
	"chevrons-up",
	"chrome",
	"circle",
	"clipboard",
	"clock",
	"cloud",
	"cloud-drizzle",
	"cloud-lightning",
	"cloud-off",
	"cloud-rain",
	"cloud-snow",
	"code",
	"codepen",
	"codesandbox",
	"coffee",
	"columns",
	"command",
	"compass",
	"copy",
	"corner-down-left",
	"corner-down-right",
	"corner-left-down",
	"corner-left-up",
	"corner-right-down",
	"corner-right-up",
	"corner-up-left",
	"corner-up-right",
	"cpu",
	"credit-card",
	"crop",
	"crosshair",
	"database",
	"delete",
	"disc",
	"divide",
	"divide-circle",
	"divide-square",
	"dollar-sign",
	"download",
	"download-cloud",
	"dribbble",
	"droplet",
	"edit",
	"edit-2",
	"edit-3",
	"external-link",
	"eye",
	"eye-off",
	"facebook",
	"fast-forward",
	"feather",
	"figma",
	"file",
	"file-minus",
	"file-plus",
	"file-text",
	"film",
	"filter",
	"flag",
	"folder",
	"folder-minus",
	"folder-plus",
	"framer",
	"frown",
	"gift",
	"git-branch",
	"git-commit",
	"git-merge",
	"git-pull-request",
	"github",
	"gitlab",
	"globe",
	"grid",
	"hard-drive",
	"hash",
	"headphones",
	"heart",
	"help-circle",
	"hexagon",
	"home",
	"image",
	"inbox",
	"info",
	"instagram",
	"italic",
	"key",
	"layers",
	"layout",
	"life-buoy",
	"link",
	"link-2",
	"linkedin",
	"list",
	"loader",
	"lock",
	"log-in",
	"log-out",
	"mail",
	"map",
	"map-pin",
	"maximize",
	"maximize-2",
	"meh",
	"menu",
	"message-circle",
	"message-square",
	"mic",
	"mic-off",
	"minimize",
	"minimize-2",
	"minus",
	"minus-circle",
	"minus-square",
	"monitor",
	"moon",
	"more-horizontal",
	"more-vertical",
	"mouse-pointer",
	"move",
	"music",
	"navigation",
	"navigation-2",
	"octagon",
	"package",
	"paperclip",
	"pause",
	"pause-circle",
	"pen-tool",
	"percent",
	"phone",
	"phone-call",
	"phone-forwarded",
	"phone-incoming",
	"phone-missed",
	"phone-off",
	"phone-outgoing",
	"pie-chart",
	"play",
	"play-circle",
	"plus",
	"plus-circle",
	"plus-square",
	"pocket",
	"power",
	"printer",
	"radio",
	"refresh-ccw",
	"refresh-cw",
	"repeat",
	"rewind",
	"rotate-ccw",
	"rotate-cw",
	"rss",
	"save",
	"scissors",
	"search",
	"send",
	"server",
	"settings",
	"share",
	"share-2",
	"shield",
	"shield-off",
	"shopping-bag",
	"shopping-cart",
	"shuffle",
	"sidebar",
	"skip-back",
	"skip-forward",
	"slack",
	"slash",
	"sliders",
	"smartphone",
	"smile",
	"speaker",
	"square",
	"star",
	"stop-circle",
	"sun",
	"sunrise",
	"sunset",
	"tablet",
	"tag",
	"target",
	"terminal",
	"thermometer",
	"thumbs-down",
	"thumbs-up",
	"toggle-left",
	"toggle-right",
	"tool",
	"trash",
	"trash-2",
	"trello",
	"trending-down",
	"trending-up",
	"triangle",
	"truck",
	"tv",
	"twitch",
	"twitter",
	"type",
	"umbrella",
	"underline",
	"unlock",
	"upload",
	"upload-cloud",
	"user",
	"user-check",
	"user-minus",
	"user-plus",
	"user-x",
	"users",
	"video",
	"video-off",
	"voicemail",
	"volume",
	"volume-1",
	"volume-2",
	"volume-x",
	"watch",
	"wifi",
	"wifi-off",
	"wind",
	"x",
	"x-circle",
	"x-octagon",
	"x-square",
	"youtube",
	"zap",
	"zap-off",
	"zoom-in",
	"zoom-out",
];
var moduleBaseUrl = "https://framer.com/m/feather-icons/";
var uppercaseIconKeys = iconKeys.map(
	(name) => name.charAt(0).toUpperCase() + name.slice(1),
);
var lowercaseIconKeyPairs = iconKeys.reduce((res, key) => {
	res[key.toLowerCase()] = key;
	return res;
}, {});
function Icon(props) {
	const {
		color,
		selectByList,
		iconSearch,
		iconSelection,
		onClick,
		onMouseDown,
		onMouseUp,
		onMouseEnter,
		onMouseLeave,
		mirrored,
	} = props;
	const isMounted = useRef(false);
	const iconKey = useIconSelection(
		iconKeys,
		selectByList,
		iconSearch,
		iconSelection,
		lowercaseIconKeyPairs,
	);
	const [SelectedIcon, setSelectedIcon] = useState(
		iconKey === "Home" ? s(React2) : null,
	);
	async function importModule() {
		let active = true;
		try {
			const iconModuleUrl = `${moduleBaseUrl}${iconKey}.js@0.0.29`;
			const module = await import(
				/* webpackIgnore: true */
				/* @vite-ignore */
				iconModuleUrl
			);
			if (active) setSelectedIcon(module.default(React2));
		} catch (e) {
			console.log(e);
			if (active) setSelectedIcon(null);
		}
		return () => {
			active = false;
		};
	}
	useEffect(() => {
		importModule();
	}, [iconKey]);
	const isOnCanvas = RenderTarget.current() === RenderTarget.canvas;
	const emptyState = isOnCanvas ? <NullState /> : null;
	return (
		<div
			style={{
				display: "contents",
			}}
			onClick={onClick}
			onMouseEnter={onMouseEnter}
			onMouseLeave={onMouseLeave}
			onMouseDown={onMouseDown}
			onMouseUp={onMouseUp}
		>
			{SelectedIcon ? (
				<SelectedIcon
					style={{
						width: "100%",
						height: "100%",
						transform: mirrored ? "scale(-1, 1)" : void 0,
					}}
					color={color}
				/>
			) : (
				emptyState
			)}
		</div>
	);
}
Icon.displayName = "Feather";
Icon.defaultProps = {
	width: 24,
	height: 24,
	iconSelection: "home",
	iconSearch: "Home",
	color: "#66F",
	selectByList: true,
	mirrored: false,
};
addPropertyControls(Icon, {
	selectByList: {
		type: ControlType2.Boolean,
		title: "Select",
		enabledTitle: "List",
		disabledTitle: "Search",
		defaultValue: Icon.defaultProps.selectByList,
	},
	iconSelection: {
		type: ControlType2.Enum,
		options: iconKeys,
		optionTitles: uppercaseIconKeys,
		defaultValue: Icon.defaultProps.iconSelection,
		title: "Name",
		hidden: ({ selectByList }) => !selectByList,
		description:
			"Find every icon name on the [Feather site](https://feathericons.com/)",
	},
	iconSearch: {
		type: ControlType2.String,
		title: "Name",
		placeholder: "Menu, Wifi, Box\u2026",
		hidden: ({ selectByList }) => selectByList,
	},
	mirrored: {
		type: ControlType2.Boolean,
		enabledTitle: "Yes",
		disabledTitle: "No",
		defaultValue: Icon.defaultProps.mirrored,
	},
	color: {
		type: ControlType2.Color,
		title: "Color",
		defaultValue: Icon.defaultProps.color,
	},
	...defaultEvents,
});

// /:https://framerusercontent.com/modules/gWFumn3jFcGYz6tuD9Hb/t69I5ux4Wsx24Gu7oJfa/GWxCRUDr_.js
var FeatherFonts = getFonts(Icon);
var enabledGestures = {
	ydypsCYw3: {
		hover: true,
	},
};
var serializationHash = "framer-H1wuf";
var variantClassNames = {
	ydypsCYw3: "framer-v-x3e66",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.4, 0, 0.2, 1],
	type: "tween",
};
var transformTemplate1 = (_, t) => `translateX(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React3.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React3.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React3.Fragment);
var getProps = ({ height, iconName, id, link, title, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		f4kscTHY5:
			(_ref =
				iconName !== null && iconName !== void 0
					? iconName
					: props.f4kscTHY5) !== null && _ref !== void 0
				? _ref
				: "Home",
		xtysok8uU:
			(_ref1 = title !== null && title !== void 0 ? title : props.xtysok8uU) !==
				null && _ref1 !== void 0
				? _ref1
				: "Home",
		y9AZl9t1i: link !== null && link !== void 0 ? link : props.y9AZl9t1i,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React3.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		f4kscTHY5,
		y9AZl9t1i,
		xtysok8uU,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "ydypsCYw3",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React3.useRef(null);
	const defaultLayoutId = React3.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={y9AZl9t1i} openInNewTab={false} smoothScroll={true}>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-x3e66", className, classNames)} framer-19s5cxx`}
							data-framer-name={"Desktop"}
							layoutDependency={layoutDependency}
							layoutId={"ydypsCYw3"}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								borderBottomLeftRadius: "50%",
								borderBottomRightRadius: "50%",
								borderTopLeftRadius: "50%",
								borderTopRightRadius: "50%",
								...style,
							}}
							{...addPropertyOverrides(
								{
									"ydypsCYw3-hover": {
										"data-framer-name": void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-1drsfbq"}
								layoutDependency={layoutDependency}
								layoutId={"bbZR7lSGy"}
								style={{
									backgroundColor: "rgba(255, 255, 255, 0.1)",
									borderBottomLeftRadius: 8,
									borderBottomRightRadius: 8,
									borderTopLeftRadius: 8,
									borderTopRightRadius: 8,
									opacity: 0,
								}}
								transformTemplate={transformTemplate1}
								variants={{
									"ydypsCYw3-hover": {
										opacity: 1,
									},
								}}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-maovdk"}
									fonts={["GF;Poppins-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"cV9z6JDKp"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-21af2431-d15e-4a85-9353-e1e449dcf92c, rgb(255, 255, 255))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
										"--framer-paragraph-spacing": "0px",
									}}
									text={xtysok8uU}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React3.Fragment>
										<motion.p
											style={{
												"--font-selector": "R0Y7UG9wcGlucy1yZWd1bGFy",
												"--framer-font-family":
													'"Poppins", "Poppins Placeholder", sans-serif',
												"--framer-font-size": "12px",
												"--framer-line-height": "12px",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-21af2431-d15e-4a85-9353-e1e449dcf92c, rgb(255, 255, 255)))",
											}}
										>
											{"Home"}
										</motion.p>
									</React3.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-1de4haz"}
								data-framer-name={"Icon"}
								layoutDependency={layoutDependency}
								layoutId={"v7kH23E8F"}
								style={{
									backgroundColor: "rgba(255, 255, 255, 0)",
									borderBottomLeftRadius: 6,
									borderBottomRightRadius: 6,
									borderTopLeftRadius: 6,
									borderTopRightRadius: 6,
								}}
							>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-1nnads7-container"}
										layoutDependency={layoutDependency}
										layoutId={"yI2NQVEnu-container"}
									>
										<Icon
											color={
												"var(--token-182ee8b3-4984-4a8e-9e60-5c8c5b4cb4cf, rgb(255, 255, 255))"
											}
											height={"100%"}
											iconSearch={f4kscTHY5}
											iconSelection={"home"}
											id={"yI2NQVEnu"}
											layoutId={"yI2NQVEnu"}
											mirrored={false}
											selectByList={false}
											style={{
												height: "100%",
												width: "100%",
											}}
											width={"100%"}
										/>
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-H1wuf.framer-19s5cxx, .framer-H1wuf .framer-19s5cxx { display: block; }",
	".framer-H1wuf.framer-x3e66 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 30px; justify-content: center; overflow: visible; padding: 0px; position: relative; text-decoration: none; width: 30px; }",
	".framer-H1wuf .framer-1drsfbq { align-content: center; align-items: center; bottom: 0px; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; left: 50%; overflow: hidden; padding: 4px 10px 4px 10px; pointer-events: none; position: absolute; width: min-content; will-change: var(--framer-will-change-override, transform); z-index: -1; }",
	".framer-H1wuf .framer-maovdk { flex: none; height: auto; position: relative; white-space: pre; width: auto; z-index: 1; }",
	".framer-H1wuf .framer-1de4haz { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 4px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-H1wuf .framer-1nnads7-container { flex: none; height: 20px; position: relative; width: 20px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-H1wuf.framer-x3e66, .framer-H1wuf .framer-1drsfbq, .framer-H1wuf .framer-1de4haz { gap: 0px; } .framer-H1wuf.framer-x3e66 > *, .framer-H1wuf .framer-1drsfbq > *, .framer-H1wuf .framer-1de4haz > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-H1wuf.framer-x3e66 > :first-child, .framer-H1wuf .framer-1drsfbq > :first-child, .framer-H1wuf .framer-1de4haz > :first-child { margin-left: 0px; } .framer-H1wuf.framer-x3e66 > :last-child, .framer-H1wuf .framer-1drsfbq > :last-child, .framer-H1wuf .framer-1de4haz > :last-child { margin-right: 0px; } }",
	".framer-H1wuf.framer-v-x3e66.hover .framer-1drsfbq { bottom: -30px; }",
];
var FramerGWxCRUDr_ = withCSS(Component, css, "framer-H1wuf");
var stdin_default = FramerGWxCRUDr_;
FramerGWxCRUDr_.displayName = "Nav Icon";
FramerGWxCRUDr_.defaultProps = {
	height: 30,
	width: 30,
};
addPropertyControls2(FramerGWxCRUDr_, {
	f4kscTHY5: {
		defaultValue: "Home",
		placeholder: "",
		title: "Icon Name",
		type: ControlType3.String,
	},
	y9AZl9t1i: {
		title: "Link",
		type: ControlType3.Link,
	},
	xtysok8uU: {
		defaultValue: "Home",
		displayTextArea: false,
		title: "Title",
		type: ControlType3.String,
	},
});
addFonts(
	FramerGWxCRUDr_,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Poppins",
					source: "google",
					style: "normal",
					url: "https://fonts.gstatic.com/s/poppins/v21/pxiEyp8kv8JHgFVrFJXUc1NECPY.woff2",
					weight: "400",
				},
			],
		},
		...FeatherFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/rjfVl88mUXTB7aIghRam/R3yeWMgqh7RWFVgbTNTH/YSYwvHiaF.js
var NavIconFonts = getFonts2(stdin_default);
var serializationHash2 = "framer-HOGmq";
var variantClassNames2 = {
	MqRw8b3u2: "framer-v-1b50eh0",
};
var transition12 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition2 = ({ value, children }) => {
	const config = React4.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React4.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React4.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React4.forwardRef(function (props, ref) {
	const fallbackRef = useRef3(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React4.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const { style, className, layoutId, variant, ...restProps } =
		getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "MqRw8b3u2",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	const router = useRouter();
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.nav
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1b50eh0",
							className,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"MqRw8b3u2"}
						ref={refBinding}
						style={{
							backgroundColor: "rgba(255, 255, 255, 0.03)",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							...style,
						}}
					>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<ComponentViewportProvider2
									height={36}
									width={"36px"}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 48) - 0 - 36) / 2)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-rpfd97-container"}
										data-framer-name={"Nav Icon"}
										layoutDependency={layoutDependency}
										layoutId={"XmTTQNXJb-container"}
										name={"Nav Icon"}
										nodeId={"XmTTQNXJb"}
										rendersWithMotion={true}
										scopeId={"YSYwvHiaF"}
									>
										{_jsx4(stdin_default, {
											f4kscTHY5: "Home",
											height: "100%",
											id: "XmTTQNXJb",
											layoutId: "XmTTQNXJb",
											name: "Nav Icon",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
											xtysok8uU: "Home",
											y9AZl9t1i: resolvedLinks[0],
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "anMi4_oPG",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks1) => (
								<ComponentViewportProvider2
									height={36}
									width={"36px"}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 48) - 0 - 36) / 2)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-up9jw6-container"}
										layoutDependency={layoutDependency}
										layoutId={"hyyuBwJhU-container"}
										nodeId={"hyyuBwJhU"}
										rendersWithMotion={true}
										scopeId={"YSYwvHiaF"}
									>
										{_jsx4(stdin_default, {
											f4kscTHY5: "folder",
											height: "100%",
											id: "hyyuBwJhU",
											layoutId: "hyyuBwJhU",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
											xtysok8uU: "Projects",
											y9AZl9t1i: resolvedLinks1[0],
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "VackNEXEB",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks2) => (
								<ComponentViewportProvider2
									height={36}
									width={"36px"}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 48) - 0 - 36) / 2)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-aodqsd-container"}
										layoutDependency={layoutDependency}
										layoutId={"E9iEmkemE-container"}
										nodeId={"E9iEmkemE"}
										rendersWithMotion={true}
										scopeId={"YSYwvHiaF"}
									>
										{_jsx4(stdin_default, {
											f4kscTHY5: "briefcase",
											height: "100%",
											id: "E9iEmkemE",
											layoutId: "E9iEmkemE",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
											xtysok8uU: "Experience",
											y9AZl9t1i: resolvedLinks2[0],
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "VkQTlRoLR",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks3) => (
								<ComponentViewportProvider2
									height={36}
									width={"36px"}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 48) - 0 - 36) / 2)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-10ujk5w-container"}
										layoutDependency={layoutDependency}
										layoutId={"dlptCH3m3-container"}
										nodeId={"dlptCH3m3"}
										rendersWithMotion={true}
										scopeId={"YSYwvHiaF"}
									>
										{_jsx4(stdin_default, {
											f4kscTHY5: "tool",
											height: "100%",
											id: "dlptCH3m3",
											layoutId: "dlptCH3m3",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
											xtysok8uU: "Tools",
											y9AZl9t1i: resolvedLinks3[0],
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
						<ResolveLinks
							links={[
								{
									href: {
										webPageId: "aX8JJ_U82",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks4) => (
								<ComponentViewportProvider2
									height={36}
									width={"36px"}
									y={
										(componentViewport?.y || 0) +
										(0 + ((componentViewport?.height || 48) - 0 - 36) / 2)
									}
								>
									<SmartComponentScopedContainer
										className={"framer-bi3p1i-container"}
										layoutDependency={layoutDependency}
										layoutId={"nuu5EG0Mr-container"}
										nodeId={"nuu5EG0Mr"}
										rendersWithMotion={true}
										scopeId={"YSYwvHiaF"}
									>
										{_jsx4(stdin_default, {
											f4kscTHY5: "edit",
											height: "100%",
											id: "nuu5EG0Mr",
											layoutId: "nuu5EG0Mr",
											style: {
												height: "100%",
												width: "100%",
											},
											width: "100%",
											xtysok8uU: "Thoughts",
											y9AZl9t1i: resolvedLinks4[0],
										})}
									</SmartComponentScopedContainer>
								</ComponentViewportProvider2>
							)}
						</ResolveLinks>
					</motion2.nav>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HOGmq.framer-lbvnzv, .framer-HOGmq .framer-lbvnzv { display: block; }",
	".framer-HOGmq.framer-1b50eh0 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 18px; height: 48px; justify-content: center; overflow: visible; padding: 0px 20px 0px 20px; position: relative; width: min-content; }",
	".framer-HOGmq .framer-rpfd97-container, .framer-HOGmq .framer-up9jw6-container, .framer-HOGmq .framer-aodqsd-container, .framer-HOGmq .framer-10ujk5w-container, .framer-HOGmq .framer-bi3p1i-container { flex: none; height: 36px; position: relative; width: 36px; }",
];
var FramerYSYwvHiaF = withCSS2(Component2, css2, "framer-HOGmq");
var stdin_default2 = FramerYSYwvHiaF;
FramerYSYwvHiaF.displayName = "NavBar - Links";
FramerYSYwvHiaF.defaultProps = {
	height: 48,
	width: 292,
};
addFonts2(
	FramerYSYwvHiaF,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...NavIconFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-bar-links
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	HPLcoRTLk: {
		path: "/404",
	},
	V_b5a_z28: {
		path: "/blog/:slug",
	},
	VackNEXEB: {
		path: "/experience",
	},
	VkQTlRoLR: {
		path: "/tools",
	},
	aX8JJ_U82: {
		path: "/blog",
	},
	anMi4_oPG: {
		path: "/projects",
	},
	augiA20Il: {
		path: "/",
	},
};

// virtual:nav-bar-links
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"93c2e84eadc6f777dd16b68f47c6cd77b9eeea21ecef5735468e2a0ce39ae610"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavBarLinksFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"93c2e84eadc6f777dd16b68f47c6cd77b9eeea21ecef5735468e2a0ce39ae610"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var nav_bar_links_default = ComponentWithRoot;
export { nav_bar_links_default as default };
